### ISSUE TITLE
Aviso/Recordatorio Clase

### ISSUE THREAD

**Issue by JuanCrg90** [UG-Mobile2016/Temario#20]
Compañeros como les comenté el pasado Jueves, esta semana tendré que ausentarme por cuestiones de trabajo. Como acordamos 

**La Reposición de clase se dará mañana Lunes 17 de octubre a las 9:30 PM por google hangout.**

 Pegaré la liga de la sala de llamada en este Issue para que estén pendientes, y le comenten a sus compañeros que no siguen el repositorio o que no hayan ido a clase el jueves pasado.

**Preparen sus dudas de lo visto hasta el momento (incluyendo problemas con butterknife)**

https://hangouts.google.com/call/lveevqgqovh6lca2vw6euaiu5ye

Saludos.

**Comment by FranciscoRam** [comment]
Enterado

**Comment by EmilioSalgado** [comment]
Enterado

**Comment by ShadowAlec** [comment]
Enterado.

**Comment by tzohpilotl** [comment]
Enterado. Tengo clase a las 10.

**Comment by Oswaldofm17** [comment]
Enterado

**Comment by AlGuerrero** [comment]
enterado

**Comment by AnaGabrielaGP** [comment]
Enterado

**Comment by JuanDanielTellezPonce** [comment]
Enterado.

**Comment by franciscop1s3** [comment]
Enterado

**Comment by cafetorres** [comment]
Enterado

**Comment by OscarGovea** [comment]
Enterado

**Comment by JuanCrg90** [comment]
https://hangouts.google.com/call/lveevqgqovh6lca2vw6euaiu5ye

**Comment by ShadowAlec** [comment]
Dice que la videollamada está llena.

**Comment by AnaGabrielaGP** [comment]
Disculpen, no puedo unirme a la videollamada, trato de unirme y me aparece una ventana que indica que está llena.

**Comment by JuanCrg90** [comment]
entren ya, ya hay espacio

**Comment by EmilioSalgado** [comment]
este no es un buen medio para la clase, en fin no tengo dudas es solo que no me dejaba usar el micrófono para decirlo

**Comment by JuanCrg90** [comment]
esta bien, ya que regrese hacemos otra clase de reposición en forma. una disculpa
